### ISSUE TITLE
Embedded list not display in IE (any version)

### ISSUE THREAD

**Issue by kblizeck** [andreasmb/lever-jobs-embed#9]
The Lever Jobs listing embed code is not triggering/showing in IE. There are no console log errors.

Here's the code we've included:
```
<div id="lever-jobs-container"></div>
<script type="text/javascript">window.leverJobsOptions = {accountName: 'ouraccountname', includeCss: true};</script>
<script type="text/javascript" src="https://andreasmb.github.io/lever-jobs-embed/index.js"></script>
```

Can you please assist?

**Comment by andreasmb** [comment]
Hi @kblizeck ! 

Some versions of IE doesn't interpret the API data as a JSON object, but I believe that's been mitigated – see https://github.com/andreasmb/lever-jobs-embed/blob/b5673b26e681ffcd4a2445939a1e77ab970eb347/index.js#L52

Are you seeing any console errors?

**Comment by andreasmb** [comment]
It looks like the findIndex method isn't supported by IE11 and older. I added a polyfill to support add support. Let me know if you're seeing any more issues with IE.
